Make it compatible with pipx
Seb-sti1/ProjectHub pull request #3
Opened 2024-03-11 15:52 UTC by Seb-sti1

- Make into a python package
- Add entrypoint
- Add instruction for venv and installation in README

2024-03-11 21:03 UTC, toniodo requested changes
Only one typo thing to correct but the rest is fine!

2024-03-11 21:03 UTC, toniodo commented on README.md
> +To build the package to need to run
"You" instead of "to" ?

2024-03-13 07:24 UTC, Seb-sti1 commented on README.md
> +To build the package to need to run
```suggestion
To build the package you need to run
```

2024-03-13 12:40 UTC, toniodo approved these changes
Everything is fine!

2024-03-15 20:18 UTC, clementlrd reviewed
Very good work thank you !

2024-03-15 20:18 UTC, clementlrd commented on README.md
> +pipx install ./path/to/projecthub-$VERSION.tar.gz
nit: wheel file is supposed to be preferable:
https://packaging.python.org/en/latest/tutorials/packaging-projects/#:~:text=Newer%20pip%20versions%20preferentially%20install%20built%20distributions

2024-03-15 20:18 UTC, clementlrd commented on setup.py
> +    ],
We have no dependencies to install for now:
pdoc is not necessary for the code to run, same for setuptools (already installed by default now) and build which are only used to build the project. In fact, we do not even need to be in our virtual environment to build the package because it will create a new environment while building the project.

2024-03-15 20:18 UTC, clementlrd commented on requirements.txt
Same comment as in setup file, only pdoc can be considered as a dev dependency for the project. Building tools can be used from outside the project.

2024-03-15 22:50 UTC, toniodo requested changes
Little fixes

2024-03-15 22:50 UTC, toniodo commented on README.md
> +
````suggestion

### Installation of [pipx](https://github.com/pypa/pipx)

You need to install pipx in order to run the project indepedently from the current loaded environement.
Following the official repository, here is the following lines you must run using pip (otherwise for other ways, take a look at the official repo):


```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
```

Upgrade pipx with `python3 -m pip install --user --upgrade pipx`.

````

2024-03-15 22:56 UTC, clementlrd commented on README.md
> +
Personally, I don't think it's a good idea to add installation instructions linked to other software because it is subject to changes, and I think it's always a good idea to refer to the official documentation.

2024-03-15 23:17 UTC, toniodo commented on README.md
> +
I change the suggestions into a redirection to the official repo + I'll create an issue regarding the installation problem of the package

2024-03-16 12:09 UTC, toniodo commented on README.md
> +
Comment updated. Once the PR is merged, the issue can be closed.

2024-03-16 20:07 UTC, Seb-sti1 commented on README.md
> +
@clementlrd i think that with the link it's okay

2024-03-16 20:16 UTC, Seb-sti1 commented on requirements.txt
why don't you consider build as a dev dependency?

2024-03-16 23:56 UTC, clementlrd commented on requirements.txt
You can add it if you want, but for me "build" is installed outside this environment.
Also it is not necessary to work on the project and can be easily added on the fly when needed.

2024-03-17 21:40 UTC, toniodo approved these changes
Sounds good!

2024-03-17 21:42 UTC, merged